services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      - TZ=America/Edmonton
    volumes:
      - ./data:/data/
    ports:
      - 3100:7745

